-- profiles/simple_test.bpl.lua
-- Minimal profile for testing without external dependencies

return {
  name = "Simple Test Invoice",
  version = "1.0",
  output_pattern = "out/test_{{number}}.pdf",

  fields = {
    { key="number", label="Invoice Number", type="text", required=true, default="TEST-001" },
    { key="client", label="Client Name", type="text", required=true, default="Test Client" },
    { key="amount", label="Amount", type="number", required=true, default=100 },
  },

  render = function(d, helpers)
    return string.format([[
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <title>Test Invoice %s</title>
  <style>
    body { font-family: sans-serif; margin: 40px; }
    h1 { color: #333; }
    .info { background: #f0f0f0; padding: 20px; border-radius: 5px; }
  </style>
</head>
<body>
  <h1>Test Invoice %s</h1>
  <div class="info">
    <p><strong>Client:</strong> %s</p>
    <p><strong>Amount:</strong> %s</p>
  </div>
  <p>This is a test invoice generated by BUFLO.</p>
</body>
</html>
]], helpers.esc(d.number), helpers.esc(d.number),
    helpers.esc(d.client), helpers.fmt_currency(d.amount))
  end,

  validate = function(d)
    if (tonumber(d.amount) or 0) <= 0 then
      return false, "Amount must be greater than 0"
    end
    return true
  end
}
